# Site settings
title: Christopher Bowles
description: A programming portfolio

# User settings
username: Christopher Bowles
user_title: Games Programmer
email: mailto:contact@crisbwls.dev
twitter_username: https://twitter.com/av1ant
github_username:  https://github.com/Cris-Bwls

# Google-analytics
google-analytics:
  id: "UA-151091341-1"

exclude: ['package.json', 'src' , 'node_modules']
