# Site settings
title: Christopher Bowles
description: A programming portfolio

# User settings
username: Christopher Bowles
user_title: Games Programmer
email: contact@crisbwls.dev
twitter_username: av1ant
github_username:  Cris-Bwls

# Google-analytics
google-analytics:
  id: "UA-151091341-1"

exclude: ['package.json', 'src' , 'node_modules']
